#!/usr/bin/env node

var fs = require('fs');

var deps = {};

var dir = fs.readdirSync('js');
dir.forEach(function(filename) {
	// don't want any of the hidden dot files
	if (filename[0] == '.') {
		return;
	}

	var lines = fs.readFileSync('js/' + filename).toString().split('\n');
	lines.filter(function(el) { return el.indexOf('Class.makeClass') !== -1 || el.indexOf(' extends ') !== -1 }).forEach(function(line) {
		var regexes = [ 
			[/Class\.makeClass\((\w+),\s*function (\w+)/, [2,1]],
			[/class\s+(\w+)\s+extends\s+(\w+)/, [1,2]],
		];
		regexes.forEach(re => {
			var matches = line.match(re[0]);
			if (matches) {
				deps[matches[re[1][0]]] = {
					dep: matches[re[1][1]],
					file: filename,
				};
			}
		});
	});
});

var includes = [];
while (Object.keys(deps).length) {
	for (var key in deps) {
		if (!(deps[key].dep in deps)) {
			if (includes.indexOf(deps[key].file) == -1) {
				includes.push(deps[key].file);
			}
			delete(deps[key]);
		}
	}
}

console.log(includes.map(function(el) { return 'script(src="js/' + el + '")'; }).join('\n'));
